
06-02-2018 14:33:42:777 - I: 	Bot is sending to many do nothing commands, if this continues it the bot will be killed off
06-02-2018 14:33:42:777 - I: 	Bot sent to many do nothing commands, something is most likely going wrong, please fix your bot. The player's ships will all be marked as destroyed and killed off.
06-02-2018 14:33:42:778 - D: 	Executing bot with following commands python.exe "bot.py" B "C:\Users\user\Desktop\Strategi Algoritma\tubes1stima\Game Engine -  Version 1.2.2\Game Engine\Replays\2018-02-06 14-33-19-910\Phase 2 - Round 21\B"
06-02-2018 14:33:42:778 - I: 	Executing process python.exe "bot.py" B "C:\Users\user\Desktop\Strategi Algoritma\tubes1stima\Game Engine -  Version 1.2.2\Game Engine\Replays\2018-02-06 14-33-19-910\Phase 2 - Round 21\B"
06-02-2018 14:33:42:795 - I: 	Bot has 4000ms to run before it will be forcefully killed
06-02-2018 14:33:42:971 - E: 	Output from bot: Traceback (most recent call last):
06-02-2018 14:33:42:971 - E: 	Output from bot:   File "bot.py", line 234, in <module>
06-02-2018 14:33:42:971 - E: 	Output from bot:     main(args.PlayerKey)
06-02-2018 14:33:42:971 - E: 	Output from bot:   File "bot.py", line 45, in main
06-02-2018 14:33:42:971 - E: 	Output from bot:     greedy(state['OpponentMap']['Cells'], state['PlayerMap']['Owner']['Energy'], state['PlayerMap']['Owner']['Points'])
06-02-2018 14:33:42:971 - E: 	Output from bot:   File "bot.py", line 67, in greedy
06-02-2018 14:33:42:971 - E: 	Output from bot:     (x,y,direction) = read_file()
06-02-2018 14:33:42:971 - E: 	Output from bot:   File "bot.py", line 33, in read_file
06-02-2018 14:33:42:971 - E: 	Output from bot:     return (x, y, direction)
06-02-2018 14:33:42:971 - E: 	Output from bot: UnboundLocalError: local variable 'x' referenced before assignment
06-02-2018 14:33:42:982 - E: 	Output from bot: 
06-02-2018 14:33:42:982 - I: 	Output from bot: 
06-02-2018 14:33:42:985 - I: 	Your bots total execution time was 00:00:00.2074927